name: Deploy to Github Pages

on:
  push:
    branches:
    - master


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version: 22.17.0

      - name: Downloading PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build VitePress
        run: pnpm -F @talex-touch/docs run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: apps/docs/.vitepress/dist
          publish_branch: gh-pages
          # dotfiles: true

      # - name: Deploy to Pages
      #   run: |
      #     cd apps/docs/.vitepress/dist
      #     git init
      #     git config user.name "TalexDreamSoul"
      #     git config user.email "${{ secrets.GIT_EMAIL }}"
      #     git add -A
      #     git commit -m 'deploy github-pages automatically'
      #     git push -f https://talex-touch:${{ secrets.ACCESS_TOKEN }}@github.com/talex-touch/tuff.git main:gh-pages
      #     cd -
