name: pushDocs

on:
  push:
    branches: 
     - master


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version:  ${{ matrix.node }}
          
      - name: Downloading PNPM
        run: npm install -g pnpm  

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
    
      - name: Build VitePress
        run: pnpm run docs:build
      
      - name: Deploy to Pages
        run: |
          cd docs/dist 
          git init
          git config user.name "GITHUB_AUTO_WORKFLOWS"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add -A
          git commit -m 'deploy github-pages automatically'
          git push -f https://talex-touch:${{ secrets.ACCESS_TOKEN }}@github.com/talex-touch/talex-touch.git master:gh-pages
          cd -
